FROM debian:stable-slim

LABEL org.opencontainers.image.vendor=Aiven \
      org.opencontainers.image.licenses=Apache-2.0

ARG CREATED
ARG VERSION
ARG COMMIT

LABEL org.opencontainers.image.created=$CREATED \
      org.opencontainers.image.version=$VERSION \
      org.opencontainers.image.revision=$COMMIT
